# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_character_details_20180120_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
