"""
Constants to use for URLs
"""

# Game IDs
SIGNUP_GAME_ID = "4"
WITHDRAW_GAME_ID = "2"
PROCESS_SIGNUPS_GAME_ID = "1"
PENDING_GAME_ID = "3"

# Character IDs
EDITABLE_CHARACTER_ID = "1"
REVIEWABLE_CHARACTER_ID = "2"
