# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('RG', 'Recruiting'), ('PD', 'Pending'), ('RN', 'Running'), ('FN', 'Finished'), ('AR', 'Archived')], default='DR', max_length=2),
        ),
    ]
