# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0011_auto_20180116_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='character_guidelines',
            field=models.TextField(null=True),
        ),
    ]
