# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0011_auto_20180116_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='houseoffun.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='character_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
