# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0012_game_character_guidelines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='details',
            new_name='private_profile',
        ),
        migrations.AddField(
            model_name='character',
            name='public_profile',
            field=models.TextField(null=True),
        ),
    ]
