# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0014_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
