# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseoffun', '0015_character_image_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='private_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='public_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
