# Generated by Django 2.0.1 on 2018-01-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_django_2_upgrade_20180127_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesignup',
            name='status',
            field=models.CharField(choices=[('RG', 'Registered'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='RG', max_length=2),
        ),
    ]
