# Generated by Django 2.0.5 on 2018-05-27 12:09

from django.db import migrations, models
from api.app.models import Plugin


def update_threads_plugin(apps, schema_editor):
    """
    """
    plugin = Plugin.objects.get(name="Threads").first()
    plugin.default_enabled = True
    plugin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_markdown_fiels_20180208_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='default_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_threads_plugin),
    ]
