# Generated by Django 2.0.5 on 2018-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_markdown_fiels_20180208_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='default_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
