# Generated by Django 2.0.1 on 2018-01-27 12:16

import actionphase.app.util.ImageUtil
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_allow_empty_character_profiles_20180122_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=actionphase.app.util.ImageUtil.ImageUtil.character_directory_path),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='app.Comment'),
        ),
    ]
