# Generated by Django 2.0.2 on 2018-02-08 19:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180204_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
